'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),W=960,H=600;
let mode='title',keys={},player,bullets=[],enemies=[],shots=[],particles=[],stars=[],wave=1,score=0,elapsed=0,spawned=0,spawnTimer=0,waveDelay=0,shake=0,last=0,mods=[],sound=false,audio,choiceIndex=0,offers=[];
const random=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
for(let i=0;i<160;i++)stars.push({x:random(0,W),y:random(0,H),z:random(.3,1.5)});
const sprites={ship:['000010000','000121000','000121000','001222100','011222110','112222211','112222211','001101100','001001100'],scout:['110000011','011000110','012111210','001222100','000121000','001000100'],tank:['001111100','012222210','112121211','122222221','012222210','001101100'],boss:['0011100011100','0111111111110','1122222222211','1221222221221','1122222222211','0111122211110','0011000001100']};
function sprite(name,x,y,scale,palette){const map=sprites[name];for(let j=0;j<map.length;j++)for(let i=0;i<map[j].length;i++){const c=map[j][i];if(c!=='0'){ctx.fillStyle=palette[+c-1];ctx.fillRect(Math.round(x+(i-map[j].length/2)*scale),Math.round(y+(j-map.length/2)*scale),scale,scale)}}}
function tone(freq,duration,type='square',volume=.025){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq*.3),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function burst(x,y,color,n=22){for(let i=0;i<n;i++){let a=random(0,Math.PI*2),v=random(40,240);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:random(.2,.7),max:.7,color,size:random(2,7)})}shake=Math.min(12,shake+4);tone(100,.18,'sawtooth',.045)}
function reset(){player={x:W/2,y:H-85,hp:5,max:5,speed:280,cool:0,rate:.2,damage:1,spread:1,pierce:0,explosive:0,inv:2};bullets=[];enemies=[];shots=[];particles=[];mods=[];wave=1;score=0;elapsed=0;spawned=0;spawnTimer=.7;waveDelay=0;mode='play';$('#overlay').classList.add('hidden');$('#status').textContent='RUN ACTIVE';$('#pause').textContent='Ⅱ PAUSE';updateMods();announce('SECTOR 01 / INBOUND');tone(500,.3)}
function announce(s){$('#notice').textContent=s;setTimeout(()=>{if($('#notice').textContent===s)$('#notice').textContent=''},2300)}
const upgrades=[{id:'rapid',name:'RAPID FIRE',desc:'Fire 20% faster. More shots. Less mercy.',apply:()=>player.rate=Math.max(.055,player.rate*.8)},{id:'spread',name:'SPLIT SHOT',desc:'Add two projectiles to every volley.',apply:()=>player.spread+=2},{id:'power',name:'HEAVY ROUNDS',desc:'Each projectile deals +1 damage.',apply:()=>player.damage++},{id:'speed',name:'ION THRUSTERS',desc:'Move 20% faster through the crossfire.',apply:()=>player.speed*=1.2},{id:'repair',name:'HULL REPAIR',desc:'Restore 3 hull points. Stay in the fight.',apply:()=>player.hp=Math.min(player.max,player.hp+3)},{id:'armor',name:'REINFORCED HULL',desc:'+2 maximum hull. Restore 2 hull points.',apply:()=>{player.max+=2;player.hp+=2}},{id:'pierce',name:'PHASE ROUNDS',desc:'Projectiles pass through one more enemy.',apply:()=>player.pierce++},{id:'blast',name:'VOLATILE AMMO',desc:'Hits explode, damaging nearby enemies.',apply:()=>player.explosive+=.6}];
function chooseUpgrade(){mode='upgrade';keys={};offers=[...upgrades].filter(u=>!(u.id==='spread'&&player.spread>=9)).sort(()=>Math.random()-.5).slice(0,3);$('#overlay').innerHTML='<div class="eyebrow">SECTOR '+String(wave).padStart(2,'0')+' CLEARED</div><h2>SALVAGE. UPGRADE. REPEAT.</h2><p>Choose a modification for this run.</p><div class="choices">'+offers.map((u,i)=>'<button class="choice" data-upgrade="'+i+'"><small>0'+(i+1)+' / SALVAGE</small><b>'+u.name+'</b><span>'+u.desc+'</span></button>').join('')+'</div><p style="margin:22px 0 0">Press 1, 2, or 3 to choose</p>';$('#overlay').classList.remove('hidden');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>selectUpgrade(+b.dataset.upgrade))}
function selectUpgrade(i){if(mode!=='upgrade')return;const u=offers[i];u.apply();mods.push(u);updateMods();wave++;spawned=0;spawnTimer=1;waveDelay=0;shots=[];bullets=[];player.inv=2;mode='play';$('#overlay').classList.add('hidden');announce(wave%5===0?'WARNING / DREADNOUGHT APPROACHING':'SECTOR '+String(wave).padStart(2,'0')+' / INBOUND');tone(700,.2)}
function updateMods(){const counts={};mods.forEach(m=>counts[m.name]=(counts[m.name]||0)+1);$('#mods').innerHTML=mods.length?Object.entries(counts).map(([n,c])=>'<span class="mod">'+n+(c>1?' ×'+c:'')+'</span>').join(''):'<span class="emptymod">＋ Survive a sector to choose an upgrade</span>';$('#modcount').textContent=String(mods.length).padStart(2,'0')+' INSTALLED';$('#build').textContent=mods.length?mods.length+' MODIFICATIONS':'STANDARD ISSUE'}
function hurt(){if(player.inv>0)return;player.hp--;player.inv=1.5;burst(player.x,player.y,'#c5ff61',18);shake=12;if(player.hp<=0){mode='dead';keys={};burst(player.x,player.y,'#ffae57',70);$('#status').textContent='SIGNAL LOST';$('#overlay').innerHTML='<div class="eyebrow">SIGNAL LOST / RUN COMPLETE</div><h2>THE VOID TAKES EVERYONE.</h2><p>Sector '+wave+' · '+score.toLocaleString()+' points · '+formatTime(elapsed)+'</p><button class="primary" id="again">LAUNCH AGAIN ↗</button><p style="margin-top:24px">Press Enter to run it back.</p>';$('#overlay').classList.remove('hidden');$('#again').onclick=reset}}
function formatTime(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0')}
function spawn(){const boss=wave%5===0&&spawned===0,tank=!boss&&Math.random()<.22;const hp=boss?55+wave*12:tank?4+Math.floor(wave/2):1+Math.floor(wave/3);enemies.push({x:boss?W/2:random(40,W-40),y:-45,base:random(0,6),age:0,hp,max:hp,type:boss?'boss':tank?'tank':'scout',r:boss?58:tank?20:15,speed:boss?35:tank?45+wave*3:65+wave*5,fire:random(1.5,3),hit:0});spawned++}
function fire(){let n=player.spread;for(let i=0;i<n;i++){let a=(i-(n-1)/2)*.14;bullets.push({x:player.x,y:player.y-20,vx:Math.sin(a)*520,vy:-Math.cos(a)*520,damage:player.damage,pierce:player.pierce,hit:new Set()})}tone(780,.07)}
function kill(e){if(e.dead)return;e.dead=true;score+=e.type==='boss'?1500:e.type==='tank'?150:75;burst(e.x,e.y,e.type==='boss'?'#f5aa5e':'#ff775f',e.type==='boss'?85:26)}
function togglePause(){if(mode==='play'){mode='pause';$('#overlay').innerHTML='<div class="eyebrow">FLIGHT SUSPENDED</div><h2>TAKE A BREATH.</h2><button class="primary" id="resume">RESUME RUN</button>';$('#overlay').classList.remove('hidden');$('#resume').onclick=togglePause;$('#pause').textContent='▶ RESUME'}else if(mode==='pause'){mode='play';$('#overlay').classList.add('hidden');$('#pause').textContent='Ⅱ PAUSE'}keys={}}
function update(dt){for(const s of stars){s.y+=s.z*25*dt;if(s.y>H){s.y=0;s.x=random(0,W)}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.vx*=.98;p.vy*=.98}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-30*dt);if(mode!=='play')return;elapsed+=dt;player.inv-=dt;player.cool-=dt;let dx=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),dy=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),norm=Math.hypot(dx,dy)||1;player.x=clamp(player.x+dx/norm*player.speed*dt,20,W-20);player.y=clamp(player.y+dy/norm*player.speed*dt,25,H-25);if(keys.Space&&player.cool<=0){fire();player.cool=player.rate}const total=wave%5===0?1:8+wave*3;spawnTimer-=dt;if(spawned<total&&spawnTimer<=0){spawn();spawnTimer=Math.max(.25,.95-wave*.035)}for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt}for(const e of enemies){e.age+=dt;e.hit-=dt;e.y+=e.speed*dt;if(e.type==='boss'&&e.y>95){e.y=95;e.x=W/2+Math.sin(e.age*.65)*310}else e.x+=Math.sin(e.age*2+e.base)*25*dt;e.fire-=dt;if(e.fire<=0&&e.y>0){let a=Math.atan2(player.y-e.y,player.x-e.x);let count=e.type==='boss'?9:e.type==='tank'?3:1;for(let i=0;i<count;i++){let ang=a+(i-(count-1)/2)*.19;shots.push({x:e.x,y:e.y,vx:Math.cos(ang)*(130+wave*5),vy:Math.sin(ang)*(130+wave*5)})}e.fire=e.type==='boss'?.8:random(1.8,3.2)}if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+11){hurt();if(e.type!=='boss'){e.dead=true;burst(e.x,e.y,'#ff775f')}}if(e.y>H+50)e.dead=true;for(const b of bullets){if(e.dead||b.dead||b.hit.has(e))continue;if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+5){b.hit.add(e);e.hp-=b.damage;e.hit=.08;if(player.explosive){burst(b.x,b.y,'#ffb655',6);for(const nearby of enemies)if(nearby!==e&&!nearby.dead&&Math.hypot(nearby.x-e.x,nearby.y-e.y)<65){nearby.hp-=player.explosive;if(nearby.hp<=0)kill(nearby)}}if(b.pierce--<=0)b.dead=true;if(e.hp<=0)kill(e)}}}for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;if(Math.hypot(s.x-player.x,s.y-player.y)<13){s.dead=true;hurt()}}bullets=bullets.filter(b=>!b.dead&&b.y>-30&&b.x>-30&&b.x<W+30);shots=shots.filter(s=>!s.dead&&s.y<H+30&&s.y>-50&&s.x>-30&&s.x<W+30);enemies=enemies.filter(e=>!e.dead);if(spawned>=total&&!enemies.length&&mode==='play'){waveDelay+=dt;if(waveDelay>1.1)chooseUpgrade()}$('#wave').innerHTML=String(wave).padStart(2,'0')+' <small>/ '+(wave%5===0?'DREADNOUGHT':wave<5?'THE OUTER VOID':'DEEP SPACE')+'</small>';$('#hull').textContent='▰ '.repeat(Math.max(0,player.hp))+'▱ '.repeat(Math.max(0,player.max-player.hp));$('#score').textContent=String(score).padStart(6,'0');$('#time').textContent=formatTime(elapsed)}
function draw(){ctx.fillStyle='#080c18';ctx.fillRect(0,0,W,H);ctx.save();if(shake>0)ctx.translate(random(-shake,shake),random(-shake,shake));for(const s of stars){ctx.fillStyle=s.z>1.1?'#7e93ad':'#293b55';ctx.fillRect(s.x|0,s.y|0,s.z>1.3?2:1,s.z>1.3?3:1)}ctx.strokeStyle='#142039';ctx.lineWidth=1;ctx.beginPath();ctx.arc(790,190,105,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(790,190,108,0,Math.PI*2);ctx.stroke();if(mode==='title'){sprite('ship',W/2,H-85,4,['#789c54','#dbffb0']);sprite('scout',140,150,3,['#823f51','#da6c7a']);sprite('scout',820,410,3,['#823f51','#da6c7a']);sprite('tank',170,450,4,['#5f456e','#ae7eaf'])}if(player&&mode!=='title'&&mode!=='dead'){if(player.inv<=0||Math.floor(player.inv*12)%2===0){ctx.fillStyle='#ffae54';ctx.fillRect(player.x-8,player.y+15,5,random(8,20));ctx.fillRect(player.x+4,player.y+15,5,random(8,20));sprite('ship',player.x,player.y,3,['#729249','#d5ff9f'])}}for(const b of bullets){ctx.fillStyle='#496a29';ctx.fillRect(b.x-3,b.y-8,6,19);ctx.fillStyle='#d5ff8f';ctx.fillRect(b.x-1,b.y-8,3,12)}for(const e of enemies){sprite(e.type,e.x,e.y,e.type==='boss'?8:e.type==='tank'?4:3,e.hit>0?['#fff','#fff']:e.type==='boss'?['#986148','#ffc16f']:['#9e405a','#ff8790']);if(e.type==='boss'){ctx.fillStyle='#402c32';ctx.fillRect(260,18,440,7);ctx.fillStyle='#ff9272';ctx.fillRect(260,18,440*e.hp/e.max,7)}}for(const s of shots){ctx.fillStyle='#672e53';ctx.fillRect(s.x-5,s.y-5,10,10);ctx.fillStyle='#ff799a';ctx.fillRect(s.x-2,s.y-2,5,5)}for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.life>.45?'#fff0cc':p.color;ctx.fillRect(p.x|0,p.y|0,p.size|0,p.size|0)}ctx.globalAlpha=1;ctx.restore();ctx.fillStyle='#00000013';for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1)}
function frame(t){const dt=Math.min((t-last)/1000,.035);last=t;update(dt);draw();requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape')togglePause();if((mode==='title'||mode==='dead')&&e.code==='Enter')reset();if(mode==='upgrade'&&['Digit1','Digit2','Digit3'].includes(e.code))selectUpgrade(+e.code.slice(-1)-1)});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{keys={};if(mode==='play')togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')togglePause()});$('#start').onclick=reset;$('#pause').onclick=togglePause;$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'SOUND ON':'SOUND OFF';if(sound)tone(440,.1)};document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false});requestAnimationFrame(frame);
