'use strict';
(()=>{
let socket=null,me=null,state=null,previous=null,received=0,lastEvent=0,lastShot=0,uiKey='',inputTime=0,session=0;
const overlay=$('#overlay'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const descriptions={rapid:['RAPID FIRE','20% faster firing'],spread:['SPLIT SHOT','Two more projectiles'],power:['HEAVY ROUNDS','+1 projectile damage'],speed:['ION THRUSTERS','20% faster movement'],repair:['HULL REPAIR','Restore 3 hull'],armor:['REINFORCED HULL','+2 max hull and repair 2'],pierce:['PHASE ROUNDS','Pierce one more enemy'],blast:['VOLATILE AMMO','Explosive splash damage']};
const bar=document.createElement('div');bar.id='netbar';bar.className='hidden';$('.arena').before(bar);
function send(value){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(value))}
function endpoint(){const q=new URLSearchParams(location.search).get('server');return q||window.VOIDRUNNER_SERVER||(!location.hostname.endsWith('github.io')&&location.protocol!=='file:'?location.origin:'')}
function openOnline(){window.netActive=true;keys={};mode='online';$('#pause').textContent='? HELP';bar.classList.add('hidden');uiKey='';overlay.classList.remove('hidden');overlay.innerHTML='<div class="eyebrow">ONLINE CO-OP / 1–4 PILOTS</div><h2>FORM YOUR SQUAD.</h2><p>One arena. Four ships. Survive together.</p><div class="netform"><label>PILOT NAME<input id="pilotname" maxlength="16" value="Pilot" autocomplete="nickname"></label><label>ROOM CODE<input id="roomcode" maxlength="6" placeholder="6-character code" autocapitalize="characters"></label><div class="netrow"><button class="primary" id="createRoom">CREATE ROOM</button><button id="joinRoom">JOIN ROOM</button></div><details id="connection"><summary>Server connection</summary><label>SERVER ADDRESS<input id="serverurl" placeholder="https://your-server.onrender.com" value="'+esc(endpoint())+'"></label></details></div><div class="neterror" id="neterror" role="status"></div><button id="backSolo">BACK TO SOLO</button>';
if(!endpoint()){$('#connection').open=true;$('#neterror').textContent='A multiplayer server needs to be deployed first. Enter its address here.'}$('#createRoom').onclick=()=>connect('create');$('#joinRoom').onclick=()=>connect('join');$('#backSolo').onclick=()=>location.href=location.pathname;}
function connect(action){if(action==='join'&&!/^[A-Z2-9]{6}$/.test($('#roomcode').value.toUpperCase())){$('#neterror').textContent='Enter a six-character room code.';return}let url;try{url=new URL($('#serverurl').value.trim());if(!['https:','http:','ws:','wss:'].includes(url.protocol)||url.username||url.password)throw Error();url.protocol=url.protocol==='https:'||url.protocol==='wss:'?'wss:':'ws:';url.pathname='/';url.search='';url.hash='';if(location.protocol==='https:'&&url.protocol!=='wss:')throw Error();}catch{$('#neterror').textContent='Enter a valid HTTPS server address (HTTP works locally).';return}const message={type:action,name:$('#pilotname').value,code:$('#roomcode').value.toUpperCase()};const current=++session;socket?.close();state=null;me=null;previous=null;lastEvent=0;lastShot=0;uiKey='';socket=new WebSocket(url);$('#neterror').textContent='Connecting… A sleeping server may take a minute.';$('#createRoom').disabled=$('#joinRoom').disabled=true;const timeout=setTimeout(()=>{if(current===session&&socket.readyState!==WebSocket.OPEN){socket.close();error('Connection timed out. Check the server address and try again.')}},65000);socket.onopen=()=>{clearTimeout(timeout);send(message)};socket.onerror=()=>{if(current===session)error('Could not connect. Check the server is running and retry.')};socket.onclose=()=>{clearTimeout(timeout);if(current!==session)return;keys={};error(state?'Connection lost. This pilot left the run. Return to the lobby to create or join a new run.':'Connection closed. Check the server address and retry.')};socket.onmessage=e=>{if(current!==session)return;let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='joined'){me=m.id;bar.classList.remove('hidden')}if(m.type==='error'){error(m.message);return}if(m.type==='state'){previous=state;state=m;received=performance.now();for(const ev of m.events){if(ev.id>lastEvent){burst(ev.x,ev.y,ev.color,ev.n);lastEvent=ev.id}}const mine=m.bullets.filter(b=>b.owner===me);if(mine.some(b=>b.id>lastShot)){tone(780,.07);lastShot=Math.max(...mine.map(b=>b.id),lastShot)}renderUI()}};}
function error(message){if(!state){const el=$('#neterror');if(el)el.textContent=message;const c=$('#createRoom'),j=$('#joinRoom');if(c)c.disabled=false;if(j)j.disabled=false;return}overlay.classList.remove('hidden');overlay.innerHTML='<div class="eyebrow">CONNECTION INTERRUPTED</div><h2>SIGNAL LOST.</h2><p class="online-note">'+esc(message)+'</p><button id="netReturn">RETURN TO LOBBY</button>';$('#netReturn').onclick=leave;}
function leave(){session++;send({type:'leave'});socket?.close();socket=null;state=null;me=null;keys={};particles=[];openOnline()}
function renderUI(){if(!state||!me)return;const p=state.players.find(p=>p.id===me);if(!p)return;bar.innerHTML='<span>ROOM <b>'+esc(state.code)+'</b></span><div class="roster">'+state.players.map(a=>'<span style="color:'+a.color+'">'+esc(a.name)+(a.id===me?' (YOU)':'')+' '+(a.hp>0?a.hp+'/'+a.max:'DOWN')+'</span>').join('')+'</div><button id="leaveRoom">LEAVE ROOM</button>';$('#leaveRoom').onclick=leave;
$('#wave').textContent=String(state.wave).padStart(2,'0');$('#hull').textContent=p.hp+' / '+p.max;$('#hull').style.color=p.color;$('#score').textContent=String(state.score).padStart(6,'0');$('#time').textContent=formatTime(state.time);$('#status').textContent=p.hp<=0?'DOWNED / TEAMMATE NEEDED':'SQUAD ONLINE';$('#build').textContent=state.players.length+' PILOTS';$('#modcount').textContent=p.mods.length+' INSTALLED';$('#mods').innerHTML=p.mods.map(n=>'<span class="mod">'+esc(n)+'</span>').join('')||'<span class="emptymod">Survive a sector to choose your upgrade</span>';
const key=[state.phase,state.host,state.players.map(a=>a.id+':'+a.chosen).join(','),p.chosen,state.wave].join('/');if(key===uiKey)return;uiKey=key;
if(state.phase==='play'){overlay.classList.add('hidden');return}overlay.classList.remove('hidden');
if(state.phase==='lobby'){overlay.innerHTML='<div class="eyebrow">SQUAD ASSEMBLING / '+state.players.length+' OF 4</div><h2>ROOM '+esc(state.code)+'</h2><p>Share this code and the server address with your squad.</p><div class="squad">'+state.players.map(a=>'<div class="pilotcard" style="border-color:'+a.color+'"><b style="color:'+a.color+'">'+esc(a.name)+'</b>'+(a.id===me?'YOU · ':'')+(a.id===state.host?'HOST':'READY')+'</div>').join('')+'</div>'+(state.host===me?'<button class="primary" id="startSquad">LAUNCH SQUAD</button>':'<p>Waiting for the host to launch.</p>')+'<p style="margin-top:20px">Stay near a downed teammate for 3 seconds to revive.</p>';if($('#startSquad'))$('#startSquad').onclick=()=>send({type:'start'})}
if(state.phase==='upgrade'){overlay.innerHTML='<div class="eyebrow">SECTOR CLEARED</div><h2>UPGRADE YOUR SHIP.</h2>'+(p.chosen?'<p>Upgrade installed. Waiting for your squad.</p>':'<p>Choose one. The next sector starts when everyone is ready.</p><div class="choices">'+p.offers.map((id,i)=>'<button class="choice" data-netchoice="'+i+'"><small>0'+(i+1)+'</small><b>'+descriptions[id][0]+'</b><span>'+descriptions[id][1]+'</span></button>').join('')+'</div>');document.querySelectorAll('[data-netchoice]').forEach(b=>b.onclick=()=>send({type:'choose',index:+b.dataset.netchoice}))}
if(state.phase==='dead'){overlay.innerHTML='<div class="eyebrow">SQUAD LOST</div><h2>THE VOID TAKES EVERYONE.</h2><p>Sector '+state.wave+' · '+state.score+' points · '+formatTime(state.time)+'</p>'+(state.host===me?'<button id="restartSquad" class="primary">RUN IT BACK</button>':'<p>Waiting for the host to restart.</p>');if($('#restartSquad'))$('#restartSquad').onclick=()=>send({type:'start'})}}
window.netHelp=()=>{if(state?.phase==='play')announce('ARROWS + SPACE / STAY NEAR DOWNED PILOTS TO REVIVE / ONLINE DOES NOT PAUSE')};
window.netUpdate=dt=>{for(const s of stars){s.y=(s.y+s.z*25*dt)%H}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt*30);inputTime+=dt;if(inputTime>=.05){inputTime=0;send({type:'input',input:{left:!!keys.ArrowLeft,right:!!keys.ArrowRight,up:!!keys.ArrowUp,down:!!keys.ArrowDown,fire:!!keys.Space}})}};
function smooth(entity,group){const old=previous?.[group]?.find(e=>e.id===entity.id);if(!old)return entity;const t=Math.min(1,(performance.now()-received)/50);return {...entity,x:old.x+(entity.x-old.x)*t,y:old.y+(entity.y-old.y)*t}}
window.netDraw=()=>{ctx.fillStyle='#080c18';ctx.fillRect(0,0,W,H);ctx.save();if(shake)ctx.translate(random(-shake,shake),random(-shake,shake));for(const s of stars){ctx.fillStyle=s.z>1.1?'#7e93ad':'#293b55';ctx.fillRect(s.x|0,s.y|0,2,2)}if(state){for(const item of state.players){const p=smooth(item,'players');if(p.hp<=0){ctx.strokeStyle=p.color;ctx.strokeRect(p.x-17,p.y-17,34,34);ctx.fillStyle=p.color;ctx.fillRect(p.x-20,p.y+25,40*p.revive/3,4);ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText('REVIVE',p.x,p.y-26);continue}if(p.inv<=0||Math.floor(p.inv*12)%2===0){ctx.fillStyle='#ffb35f';ctx.fillRect(p.x-5,p.y+15,8,random(8,18));sprite('ship',p.x,p.y,3,[p.color,'#e8f4ff'])}ctx.fillStyle=p.color;ctx.textAlign='center';ctx.font='bold 12px monospace';ctx.fillText(p.name+(p.id===me?' · YOU':''),p.x,p.y+40);if(p.id===me){ctx.strokeStyle=p.color;ctx.strokeRect(p.x-20,p.y-21,40,47)}}for(const item of state.enemies){const e=smooth(item,'enemies');sprite(e.type,e.x,e.y,e.type==='boss'?8:e.type==='tank'?4:3,e.type==='boss'?['#986148','#ffc16f']:['#9e405a','#ff8790']);if(e.type==='boss'){ctx.fillStyle='#402c32';ctx.fillRect(260,18,440,7);ctx.fillStyle='#ff9272';ctx.fillRect(260,18,440*e.hp/e.max,7)}}for(const item of state.bullets){const b=smooth(item,'bullets');ctx.fillStyle=b.color;ctx.fillRect(b.x-2,b.y-8,4,13)}for(const item of state.shots){const s=smooth(item,'shots');ctx.fillStyle='#ff799a';ctx.fillRect(s.x-3,s.y-3,6,6)}}for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.color;ctx.fillRect(p.x|0,p.y|0,p.size|0,p.size|0)}ctx.globalAlpha=1;ctx.restore();};
window.addEventListener('keydown',e=>{if(!window.netActive||e.repeat||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(['Digit1','Digit2','Digit3'].includes(e.code)&&state?.phase==='upgrade')send({type:'choose',index:+e.code.slice(-1)-1})});window.addEventListener('blur',()=>{keys={};send({type:'input',input:{}})});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};send({type:'input',input:{}})}});$('#online').onclick=openOnline;
})();
