import { readFile, writeFile, mkdir } from 'node:fs/promises';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
const plain=s=>s.replace(/^import .*?;\s*$/gm,'').replace(/^export /gm,'');
const script=s=>'<script>\n'+s.replace(/<\/script/gi,'<\\/script')+'\n</script>';
let html=await read('index.html');
html=html.replace('<link rel="stylesheet" href="style.css">','<style>\n'+await read('style.css')+'\n</style>');
html=html.replace('<script src="config.js"></script>',script(await read('config.js')+"\nwindow.VOIDRUNNER_SERVER ||= 'https://void-runner.onrender.com';\n"));
html=html.replace('<script src="game.js"></script>',script(await read('game.js')));
const shared=script('window.VoidShared=(()=>{\n'+plain(await read('shared/netcode.js'))+'\nreturn {STEP,moveShip,sweptHit,reconcile};})();');
const engine=script('window.VoidEngine=(()=>{const {STEP,moveShip,sweptHit}=window.VoidShared;\n'+plain(await read('shared/engine.js'))+'\nreturn {Room};})();');
const peer=script('window.VoidPeer=(()=>{const {Room}=window.VoidEngine;\n'+plain(await read('peer.js'))+'\nreturn {PeerSession};})();');
const online=script('{const {PeerSession}=window.VoidPeer;const {STEP,moveShip,reconcile}=window.VoidShared;\n'+plain(await read('online.js'))+'\n}');
html=html.replace('<script type="module" src="online.js"></script>',[shared,engine,peer,online].join('\n'));
html=html.replace(/<a[^>]+id="downloadClient"[^>]*>.*?<\/a>/,'<span class="downloadlink">PORTABLE CLIENT · SOLO WORKS OFFLINE</span>');
html=html.replace('href="./"','href="#"');
await mkdir(new URL('../downloads/',import.meta.url),{recursive:true});
await writeFile(new URL('../downloads/voidrunner.html',import.meta.url),html);
console.log('Portable client: '+Buffer.byteLength(html)+' bytes');
